# Netflix Engagement Data Inspection

This notebook inspects the structure and contents of the raw Netflix engagement reports before cleaning and combining the dataset.

In [2]:
import pandas as pd

In [1]:
import sys
print(sys.executable)

/Users/dafyddjones/.pyenv/versions/3.12.9/envs/lewagon_current/bin/python

In [3]:
import pandas as pd

print(pd.__version__)

3.0.1

In [5]:
file_path = "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2023Jan-Jun.xlsx"

excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['Engagement']

In [6]:
df_2023_h1 = pd.read_excel(file_path, sheet_name="Engagement")

df_2023_h1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,What We Watched: A Netflix Engagement Report,NaN,NaN,NaN
1,NaN,Hours viewed from January to June 2023,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,Title,Available Globally?,Release Date,Hours Viewed

In [7]:
from pathlib import Path

raw_files = list(Path("../data/raw").glob("*.xlsx"))

len(raw_files)

7

In [8]:
for file in raw_files:
    excel_file = pd.ExcelFile(file)
    print(file.name, "->", excel_file.sheet_names)

What_We_Watched_A_Netflix_Engagement_Report_2024Jan-Jun.xlsx -> ['TV', 'Film']
Netflix-s_What_We_Watched_Report_2026Jan-Jun__1_.xlsx -> ['Shows', 'Movies']
What_We_Watched_A_Netflix_Engagement_Report_2024Jul-Dec.xlsx -> ['TV', 'Film']
What_We_Watched_A_Netflix_Engagement_Report_2023Jul-Dec.xlsx -> ['TV', 'Film']
What_We_Watched_A_Netflix_Engagement_Report_2025Jan-Jun.xlsx -> ['Shows', 'Movies']
What_We_Watched_A_Netflix_Engagement_Report_2025Jul-Dec__6_.xlsx -> ['Shows', 'Movies']
What_We_Watched_A_Netflix_Engagement_Report_2023Jan-Jun.xlsx -> ['Engagement']

In [9]:
df_2023_h1 = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2023Jan-Jun.xlsx",
    sheet_name="Engagement"
)

df_2023_h1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,What We Watched: A Netflix Engagement Report,NaN,NaN,NaN
1,NaN,Hours viewed from January to June 2023,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,Title,Available Globally?,Release Date,Hours Viewed

In [11]:
df_2023_h1 = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2023Jan-Jun.xlsx",
    sheet_name="Engagement",
    header=5
)

df_2023_h1.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed
0,NaN,The Night Agent: Season 1,Yes,2023-03-23,812100000
1,NaN,Ginny & Georgia: Season 2,Yes,2023-01-05,665100000
2,NaN,The Glory: Season 1 // 더 글로리: 시즌 1,Yes,2022-12-30,622800000
3,NaN,Wednesday: Season 1,Yes,2022-11-23,507700000
4,NaN,Queen Charlotte: A Bridgerton Story,Yes,2023-05-04,503000000

In [12]:
df_2023_h1.shape

(18214, 5)

In [13]:
df_2023_h1.columns

Index(['Unnamed: 0', 'Title', 'Available Globally?', 'Release Date',
       'Hours Viewed'],
      dtype='str')

In [15]:
df_2023_h1.dtypes

Unnamed: 0                    float64
Title                             str
Available Globally?               str
Release Date           datetime64[us]
Hours Viewed                    int64
dtype: object

In [16]:
df_2023_h1.isna().sum()

Unnamed: 0             18214
Title                      0
Available Globally?        0
Release Date           13359
Hours Viewed               0
dtype: int64

In [17]:
file_2023_h2 = "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2023Jul-Dec.xlsx"

df_2023_h2_tv_raw = pd.read_excel(
    file_2023_h2,
    sheet_name="TV"
)

df_2023_h2_tv_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,What We Watched: A Netflix Engagement Report,NaN,NaN,NaN,NaN,NaN
1,NaN,Views from July to December 2023,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views

In [18]:
df_2023_h2_tv = pd.read_excel(
    file_2023_h2,
    sheet_name="TV",
    header=5
)

df_2023_h2_tv.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,ONE PIECE: Season 1,Yes,2023-08-31,541900000,7:34,71600000
1,NaN,Dear Child: Limited Series // Liebes Kind: Min...,Yes,2023-09-07,252800000,4:49,52500000
2,NaN,Who is Erin Carter?: Limited Series,Yes,2023-08-24,286200000,5:43,50100000
3,NaN,Lupin: Part 3,Yes,2023-10-05,274300000,5:31,49700000
4,NaN,The Witcher: Season 3,Yes,2023-06-29,363800000,7:36,47900000

In [19]:
df_2023_h2_film = pd.read_excel(
    file_2023_h2,
    sheet_name="Film",
    header=5
)

df_2023_h2_film.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Leave the World Behind,Yes,2023-12-08,286300000,2:22,121000000
1,NaN,Heart of Stone,Yes,2023-08-11,228400000,2:05,109600000
2,NaN,Leo,Yes,2023-11-21,171200000,1:47,96000000
3,NaN,Nowhere,Yes,2023-09-29,156600000,1:49,86200000
4,NaN,The Out-Laws,Yes,2023-07-07,135500000,1:37,83800000

In [20]:
file_2024_h1 = "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2024Jan-Jun.xlsx"

df_2024_h1_tv = pd.read_excel(
    file_2024_h1,
    sheet_name="TV",
    header=5
)

df_2024_h1_tv.columns

Index(['Unnamed: 0', 'Title', 'Available Globally?', 'Release Date',
       'Hours Viewed', 'Runtime', 'Views'],
      dtype='str')

In [21]:
file_2024_h2 = "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2024Jul-Dec.xlsx"

df_2024_h2_tv = pd.read_excel(
    file_2024_h2,
    sheet_name="TV",
    header=5
)

df_2024_h2_tv.columns

Index(['Unnamed: 0', 'Title', 'Available Globally?', 'Release Date',
       'Hours Viewed', 'Runtime', 'Views'],
      dtype='str')

In [22]:
file_2025_h1 = "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2025Jan-Jun.xlsx"

df_2025_h1_shows_raw = pd.read_excel(
    file_2025_h1,
    sheet_name="Shows"
)

df_2025_h1_shows_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,What We Watched: A Netflix Engagement Report,NaN,NaN,NaN,NaN,NaN
1,NaN,Views from January to June 2025,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views

In [23]:
df_2025_h1_shows = pd.read_excel(
    file_2025_h1,
    sheet_name="Shows",
    header=5
)

df_2025_h1_shows.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Adolescence: Limited Series,Yes,2025-03-13,555100000,3:50,144800000
1,NaN,Squid Game: Season 2 // 오징어 게임: 시즌 2,Yes,2024-12-26,840300000,7:10,117300000
2,NaN,Squid Game: Season 3 // 오징어 게임: 시즌 3,Yes,2025-06-27,438600000,6:08,71500000
3,NaN,Zero Day: Limited Series,Yes,2025-02-20,315800000,5:09,61300000
4,NaN,Missing You: Limited Series,Yes,2025-01-01,218600000,3:46,58000000

In [24]:
file_2025_h2 = "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2025Jul-Dec__6_.xlsx"

df_2025_h2_shows = pd.read_excel(
    file_2025_h2,
    sheet_name="Shows",
    header=5
)

df_2025_h2_shows.columns

Index(['Unnamed: 0', 'Title', 'Available Globally?', 'Release Date',
       'Hours Viewed', 'Runtime', 'Views'],
      dtype='str')

In [25]:
file_2026_h1 = "../data/raw/Netflix-s_What_We_Watched_Report_2026Jan-Jun__1_.xlsx"

df_2026_h1_shows_raw = pd.read_excel(
    file_2026_h1,
    sheet_name="Shows"
)

df_2026_h1_shows_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Netflix's What We Watched Report,NaN,NaN,NaN,NaN,NaN
1,NaN,Views from January to June 2026* (see footnote),NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views

In [26]:
df_2026_h1_shows = pd.read_excel(
    file_2026_h1,
    sheet_name="Shows",
    header=5
)

df_2026_h1_shows.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,His & Hers: Limited Series,Yes,2026-01-08,454300000.0,4:22,104000000
1,NaN,Bridgerton: Season 4,Yes,2026-01-29,889800000.0,8:53,100200000
2,NaN,I Will Find You: Limited Series,Yes,2026-06-18,350500000.0,5:29,63900000
3,NaN,Stranger Things 5,Yes,2025-11-26,578400000.0,10:24,55600000
4,NaN,Run Away: Limited Series,Yes,2026-01-01,315300000.0,6:16,50300000