# Netflix Engagement Data Cleaning

This notebook cleans and standardises the Netflix engagement reports before combining them into a single analysis-ready dataset.

In [1]:
import pandas as pd

In [2]:
df_2023_h1 = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2023Jan-Jun.xlsx",
    sheet_name="Engagement",
    header=5
)

df_2023_h1 = df_2023_h1.drop(columns=["Unnamed: 0"])

df_2023_h1.head()

,Title,Available Globally?,Release Date,Hours Viewed
0,The Night Agent: Season 1,Yes,2023-03-23,812100000
1,Ginny & Georgia: Season 2,Yes,2023-01-05,665100000
2,The Glory: Season 1 // 더 글로리: 시즌 1,Yes,2022-12-30,622800000
3,Wednesday: Season 1,Yes,2022-11-23,507700000
4,Queen Charlotte: A Bridgerton Story,Yes,2023-05-04,503000000

In [3]:
df_2023_h1["Report Period"] = "2023 H1"

df_2023_h1.head()

,Title,Available Globally?,Release Date,Hours Viewed,Report Period
0,The Night Agent: Season 1,Yes,2023-03-23,812100000,2023 H1
1,Ginny & Georgia: Season 2,Yes,2023-01-05,665100000,2023 H1
2,The Glory: Season 1 // 더 글로리: 시즌 1,Yes,2022-12-30,622800000,2023 H1
3,Wednesday: Season 1,Yes,2022-11-23,507700000,2023 H1
4,Queen Charlotte: A Bridgerton Story,Yes,2023-05-04,503000000,2023 H1

In [4]:
df_2023_h1["Runtime"] = pd.NA
df_2023_h1["Views"] = pd.NA

df_2023_h1.head()

,Title,Available Globally?,Release Date,Hours Viewed,Report Period,Runtime,Views
0,The Night Agent: Season 1,Yes,2023-03-23,812100000,2023 H1,<NA>,<NA>
1,Ginny & Georgia: Season 2,Yes,2023-01-05,665100000,2023 H1,<NA>,<NA>
2,The Glory: Season 1 // 더 글로리: 시즌 1,Yes,2022-12-30,622800000,2023 H1,<NA>,<NA>
3,Wednesday: Season 1,Yes,2022-11-23,507700000,2023 H1,<NA>,<NA>
4,Queen Charlotte: A Bridgerton Story,Yes,2023-05-04,503000000,2023 H1,<NA>,<NA>

In [5]:
df_2023_h1 = df_2023_h1[
    [
        "Title",
        "Available Globally?",
        "Release Date",
        "Hours Viewed",
        "Runtime",
        "Views",
        "Report Period"
    ]
]

df_2023_h1.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period
0,The Night Agent: Season 1,Yes,2023-03-23,812100000,<NA>,<NA>,2023 H1
1,Ginny & Georgia: Season 2,Yes,2023-01-05,665100000,<NA>,<NA>,2023 H1
2,The Glory: Season 1 // 더 글로리: 시즌 1,Yes,2022-12-30,622800000,<NA>,<NA>,2023 H1
3,Wednesday: Season 1,Yes,2022-11-23,507700000,<NA>,<NA>,2023 H1
4,Queen Charlotte: A Bridgerton Story,Yes,2023-05-04,503000000,<NA>,<NA>,2023 H1

In [6]:
df_2023_h1["Content Type"] = pd.NA

df_2023_h1.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,The Night Agent: Season 1,Yes,2023-03-23,812100000,<NA>,<NA>,2023 H1,<NA>
1,Ginny & Georgia: Season 2,Yes,2023-01-05,665100000,<NA>,<NA>,2023 H1,<NA>
2,The Glory: Season 1 // 더 글로리: 시즌 1,Yes,2022-12-30,622800000,<NA>,<NA>,2023 H1,<NA>
3,Wednesday: Season 1,Yes,2022-11-23,507700000,<NA>,<NA>,2023 H1,<NA>
4,Queen Charlotte: A Bridgerton Story,Yes,2023-05-04,503000000,<NA>,<NA>,2023 H1,<NA>

In [7]:
df_2023_h2_tv = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2023Jul-Dec.xlsx",
    sheet_name="TV",
    header=5
)

df_2023_h2_tv = df_2023_h2_tv.drop(columns=["Unnamed: 0"])

df_2023_h2_tv.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,ONE PIECE: Season 1,Yes,2023-08-31,541900000,7:34,71600000
1,Dear Child: Limited Series // Liebes Kind: Min...,Yes,2023-09-07,252800000,4:49,52500000
2,Who is Erin Carter?: Limited Series,Yes,2023-08-24,286200000,5:43,50100000
3,Lupin: Part 3,Yes,2023-10-05,274300000,5:31,49700000
4,The Witcher: Season 3,Yes,2023-06-29,363800000,7:36,47900000

In [8]:
df_2023_h2_tv["Report Period"] = "2023 H2"
df_2023_h2_tv["Content Type"] = "Show"

df_2023_h2_tv.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,ONE PIECE: Season 1,Yes,2023-08-31,541900000,7:34,71600000,2023 H2,Show
1,Dear Child: Limited Series // Liebes Kind: Min...,Yes,2023-09-07,252800000,4:49,52500000,2023 H2,Show
2,Who is Erin Carter?: Limited Series,Yes,2023-08-24,286200000,5:43,50100000,2023 H2,Show
3,Lupin: Part 3,Yes,2023-10-05,274300000,5:31,49700000,2023 H2,Show
4,The Witcher: Season 3,Yes,2023-06-29,363800000,7:36,47900000,2023 H2,Show

In [9]:
df_2023_h2_film = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2023Jul-Dec.xlsx",
    sheet_name="Film",
    header=5
)

df_2023_h2_film = df_2023_h2_film.drop(columns=["Unnamed: 0"])

df_2023_h2_film.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,Leave the World Behind,Yes,2023-12-08,286300000,2:22,121000000
1,Heart of Stone,Yes,2023-08-11,228400000,2:05,109600000
2,Leo,Yes,2023-11-21,171200000,1:47,96000000
3,Nowhere,Yes,2023-09-29,156600000,1:49,86200000
4,The Out-Laws,Yes,2023-07-07,135500000,1:37,83800000

In [10]:
df_2023_h2_film["Report Period"] = "2023 H2"
df_2023_h2_film["Content Type"] = "Movie"

df_2023_h2_film.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Leave the World Behind,Yes,2023-12-08,286300000,2:22,121000000,2023 H2,Movie
1,Heart of Stone,Yes,2023-08-11,228400000,2:05,109600000,2023 H2,Movie
2,Leo,Yes,2023-11-21,171200000,1:47,96000000,2023 H2,Movie
3,Nowhere,Yes,2023-09-29,156600000,1:49,86200000,2023 H2,Movie
4,The Out-Laws,Yes,2023-07-07,135500000,1:37,83800000,2023 H2,Movie

In [11]:
df_2023_h2 = pd.concat(
    [df_2023_h2_tv, df_2023_h2_film],
    ignore_index=True
)

df_2023_h2.shape

(15994, 8)

In [12]:
df_2023_h2["Content Type"].value_counts()

Content Type
Movie    9395
Show     6599
Name: count, dtype: int64

In [13]:
df_2023_h2.columns

Index(['Title', 'Available Globally?', 'Release Date', 'Hours Viewed',
       'Runtime', 'Views', 'Report Period', 'Content Type'],
      dtype='str')

In [14]:
df_2024_h1_tv = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2024Jan-Jun.xlsx",
    sheet_name="TV",
    header=5
)

df_2024_h1_tv.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Fool Me Once: Limited Series,Yes,2024-01-01,689500000,6:25,107500000
1,NaN,Bridgerton: Season 3,Yes,2024-05-16,733800000,7:59,91900000
2,NaN,Baby Reindeer: Limited Series,Yes,2024-04-11,347600000,3:58,87600000
3,NaN,The Gentlemen: Season 1,Yes,2024-03-07,507300000,6:41,75900000
4,NaN,Avatar The Last Airbender: Season 1,Yes,2024-02-22,515300000,7:15,71100000

In [15]:
df_2024_h1_tv = df_2024_h1_tv.drop(columns=["Unnamed: 0"])

df_2024_h1_tv["Report Period"] = "2024 H1"
df_2024_h1_tv["Content Type"] = "Show"

df_2024_h1_tv.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Fool Me Once: Limited Series,Yes,2024-01-01,689500000,6:25,107500000,2024 H1,Show
1,Bridgerton: Season 3,Yes,2024-05-16,733800000,7:59,91900000,2024 H1,Show
2,Baby Reindeer: Limited Series,Yes,2024-04-11,347600000,3:58,87600000,2024 H1,Show
3,The Gentlemen: Season 1,Yes,2024-03-07,507300000,6:41,75900000,2024 H1,Show
4,Avatar The Last Airbender: Season 1,Yes,2024-02-22,515300000,7:15,71100000,2024 H1,Show

In [16]:
df_2024_h1_film = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2024Jan-Jun.xlsx",
    sheet_name="Film",
    header=5
)

df_2024_h1_film.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Damsel,Yes,2024-03-08,263700000,1:50,143800000
1,NaN,Lift,Yes,2024-01-12,230800000,1:47,129400000
2,NaN,Society of the Snow // La sociedad de la nieve,Yes,2024-01-04,252500000,2:26,103800000
3,NaN,Under Paris // Sous la Seine,Yes,2024-06-05,146800000,1:44,84700000
4,NaN,The Super Mario Bros. Movie,No,NaN,123100000,1:32,80300000

In [17]:
df_2024_h1_film = df_2024_h1_film.drop(columns=["Unnamed: 0"])

df_2024_h1_film["Report Period"] = "2024 H1"
df_2024_h1_film["Content Type"] = "Movie"

df_2024_h1_film.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Damsel,Yes,2024-03-08,263700000,1:50,143800000,2024 H1,Movie
1,Lift,Yes,2024-01-12,230800000,1:47,129400000,2024 H1,Movie
2,Society of the Snow // La sociedad de la nieve,Yes,2024-01-04,252500000,2:26,103800000,2024 H1,Movie
3,Under Paris // Sous la Seine,Yes,2024-06-05,146800000,1:44,84700000,2024 H1,Movie
4,The Super Mario Bros. Movie,No,NaN,123100000,1:32,80300000,2024 H1,Movie

In [18]:
df_2024_h1 = pd.concat(
    [df_2024_h1_tv, df_2024_h1_film],
    ignore_index=True
)

df_2024_h1.shape

(16161, 8)

In [19]:
df_2024_h1["Content Type"].value_counts()

Content Type
Movie    9360
Show     6801
Name: count, dtype: int64

In [20]:
df_2024_h2_tv = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2024Jul-Dec.xlsx",
    sheet_name="TV",
    header=5
)

df_2024_h2_tv.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Squid Game: Season 2 // 오징어 게임: 시즌 2,Yes,2024-12-26,619900000,7:10,86500000
1,NaN,The Perfect Couple: Season 1,Yes,2024-09-05,383100000,5:06,75100000
2,NaN,Monsters: The Lyle and Erik Menendez Story,Yes,2024-09-19,550400000,7:54,69700000
3,NaN,Emily in Paris: Season 4,Yes,2024-08-15,344100000,5:57,57800000
4,NaN,Nobody Wants This: Season 1,Yes,2024-09-26,250900000,4:25,56800000

In [21]:
df_2024_h2_tv = df_2024_h2_tv.drop(columns=["Unnamed: 0"])

df_2024_h2_tv["Report Period"] = "2024 H2"
df_2024_h2_tv["Content Type"] = "Show"

df_2024_h2_tv.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Squid Game: Season 2 // 오징어 게임: 시즌 2,Yes,2024-12-26,619900000,7:10,86500000,2024 H2,Show
1,The Perfect Couple: Season 1,Yes,2024-09-05,383100000,5:06,75100000,2024 H2,Show
2,Monsters: The Lyle and Erik Menendez Story,Yes,2024-09-19,550400000,7:54,69700000,2024 H2,Show
3,Emily in Paris: Season 4,Yes,2024-08-15,344100000,5:57,57800000,2024 H2,Show
4,Nobody Wants This: Season 1,Yes,2024-09-26,250900000,4:25,56800000,2024 H2,Show

In [22]:
df_2024_h2_film = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2024Jul-Dec.xlsx",
    sheet_name="Film",
    header=5
)

df_2024_h2_film.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Carry-On,Yes,2024-12-13,274500000,2:00,137300000
1,NaN,The Union,Yes,2024-08-16,238200000,1:49,131100000
2,NaN,Rebel Ridge,Yes,2024-09-06,283700000,2:12,129000000
3,NaN,Beverly Hills Cop: Axel F,Yes,2024-07-03,190900000,1:58,97100000
4,NaN,Our Little Secret,Yes,2024-11-27,136800000,1:41,81300000

In [23]:
df_2024_h2_film = df_2024_h2_film.drop(columns=["Unnamed: 0"])

df_2024_h2_film["Report Period"] = "2024 H2"
df_2024_h2_film["Content Type"] = "Movie"

df_2024_h2_film.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Carry-On,Yes,2024-12-13,274500000,2:00,137300000,2024 H2,Movie
1,The Union,Yes,2024-08-16,238200000,1:49,131100000,2024 H2,Movie
2,Rebel Ridge,Yes,2024-09-06,283700000,2:12,129000000,2024 H2,Movie
3,Beverly Hills Cop: Axel F,Yes,2024-07-03,190900000,1:58,97100000,2024 H2,Movie
4,Our Little Secret,Yes,2024-11-27,136800000,1:41,81300000,2024 H2,Movie

In [24]:
df_2024_h2 = pd.concat(
    [df_2024_h2_tv, df_2024_h2_film],
    ignore_index=True
)

df_2024_h2.shape

(15563, 8)

In [25]:
df_2024_h2["Content Type"].value_counts()

Content Type
Movie    8680
Show     6883
Name: count, dtype: int64

In [26]:
df_2024_h2["Content Type"].value_counts()

Content Type
Movie    8680
Show     6883
Name: count, dtype: int64

In [27]:
df_2025_h1_shows = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2025Jan-Jun.xlsx",
    sheet_name="Shows",
    header=5
)

df_2025_h1_shows.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Adolescence: Limited Series,Yes,2025-03-13,555100000,3:50,144800000
1,NaN,Squid Game: Season 2 // 오징어 게임: 시즌 2,Yes,2024-12-26,840300000,7:10,117300000
2,NaN,Squid Game: Season 3 // 오징어 게임: 시즌 3,Yes,2025-06-27,438600000,6:08,71500000
3,NaN,Zero Day: Limited Series,Yes,2025-02-20,315800000,5:09,61300000
4,NaN,Missing You: Limited Series,Yes,2025-01-01,218600000,3:46,58000000

In [28]:
df_2025_h1_shows = df_2025_h1_shows.drop(columns=["Unnamed: 0"])

df_2025_h1_shows["Report Period"] = "2025 H1"
df_2025_h1_shows["Content Type"] = "Show"

df_2025_h1_shows.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Adolescence: Limited Series,Yes,2025-03-13,555100000,3:50,144800000,2025 H1,Show
1,Squid Game: Season 2 // 오징어 게임: 시즌 2,Yes,2024-12-26,840300000,7:10,117300000,2025 H1,Show
2,Squid Game: Season 3 // 오징어 게임: 시즌 3,Yes,2025-06-27,438600000,6:08,71500000,2025 H1,Show
3,Zero Day: Limited Series,Yes,2025-02-20,315800000,5:09,61300000,2025 H1,Show
4,Missing You: Limited Series,Yes,2025-01-01,218600000,3:46,58000000,2025 H1,Show

In [29]:
df_2025_h1_movies = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2025Jan-Jun.xlsx",
    sheet_name="Movies",
    header=5
)

df_2025_h1_movies.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Back in Action,Yes,2025-01-17,313000000,1:54,164700000
1,NaN,STRAW,Yes,2025-06-06,185200000,1:48,102900000
2,NaN,The Life List,Yes,2025-03-28,198900000,2:05,95500000
3,NaN,Exterritorial,Yes,2025-04-30,159000000,1:49,87500000
4,NaN,Havoc,Yes,2025-04-25,154900000,1:47,86900000

In [30]:
df_2025_h1_movies = df_2025_h1_movies.drop(columns=["Unnamed: 0"])

df_2025_h1_movies["Report Period"] = "2025 H1"
df_2025_h1_movies["Content Type"] = "Movie"

df_2025_h1_movies.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Back in Action,Yes,2025-01-17,313000000,1:54,164700000,2025 H1,Movie
1,STRAW,Yes,2025-06-06,185200000,1:48,102900000,2025 H1,Movie
2,The Life List,Yes,2025-03-28,198900000,2:05,95500000,2025 H1,Movie
3,Exterritorial,Yes,2025-04-30,159000000,1:49,87500000,2025 H1,Movie
4,Havoc,Yes,2025-04-25,154900000,1:47,86900000,2025 H1,Movie

In [31]:
df_2025_h1 = pd.concat(
    [df_2025_h1_shows, df_2025_h1_movies],
    ignore_index=True
)

df_2025_h1.shape

(16182, 8)

In [32]:
df_2025_h1["Content Type"].value_counts()

Content Type
Movie    8674
Show     7508
Name: count, dtype: int64

In [33]:
df_2025_h2_shows = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2025Jul-Dec__6_.xlsx",
    sheet_name="Shows",
    header=5
)

df_2025_h2_shows.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,Wednesday: Season 2,Yes,2025-08-06,964100000.0,7:47,123900000
1,NaN,Stranger Things 5,Yes,2025-11-26,879700000.0,*,93500000
2,NaN,UNTAMED: Season 1,Yes,2025-07-17,451600000.0,4:52,92800000
3,NaN,Squid Game: Season 3 // 오징어 게임: 시즌 3,Yes,2025-06-27,484300000.0,6:08,79000000
4,NaN,Stranger Things,Yes,2016-07-15,386000000.0,6:49,56600000

In [34]:
df_2025_h2_shows = df_2025_h2_shows.drop(columns=["Unnamed: 0"])

df_2025_h2_shows["Report Period"] = "2025 H2"
df_2025_h2_shows["Content Type"] = "Show"

df_2025_h2_shows.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,Wednesday: Season 2,Yes,2025-08-06,964100000.0,7:47,123900000,2025 H2,Show
1,Stranger Things 5,Yes,2025-11-26,879700000.0,*,93500000,2025 H2,Show
2,UNTAMED: Season 1,Yes,2025-07-17,451600000.0,4:52,92800000,2025 H2,Show
3,Squid Game: Season 3 // 오징어 게임: 시즌 3,Yes,2025-06-27,484300000.0,6:08,79000000,2025 H2,Show
4,Stranger Things,Yes,2016-07-15,386000000.0,6:49,56600000,2025 H2,Show

In [35]:
df_2025_h2_movies = pd.read_excel(
    "../data/raw/What_We_Watched_A_Netflix_Engagement_Report_2025Jul-Dec__6_.xlsx",
    sheet_name="Movies",
    header=5
)

df_2025_h2_movies.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,KPop Demon Hunters,Yes,2025-06-20,802600000.0,1:40,481600000
1,NaN,Happy Gilmore 2,Yes,2025-07-25,265700000.0,1:58,135100000
2,NaN,Frankenstein,Yes,2025-11-07,247300000.0,2:32,97600000
3,NaN,My Oxford Year,Yes,2025-08-01,162200000.0,1:53,86100000
4,NaN,The Old Guard 2,Yes,2025-07-02,145300000.0,1:47,81500000

In [36]:
df_2025_h2_movies = df_2025_h2_movies.drop(columns=["Unnamed: 0"])

df_2025_h2_movies["Report Period"] = "2025 H2"
df_2025_h2_movies["Content Type"] = "Movie"

df_2025_h2_movies.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,KPop Demon Hunters,Yes,2025-06-20,802600000.0,1:40,481600000,2025 H2,Movie
1,Happy Gilmore 2,Yes,2025-07-25,265700000.0,1:58,135100000,2025 H2,Movie
2,Frankenstein,Yes,2025-11-07,247300000.0,2:32,97600000,2025 H2,Movie
3,My Oxford Year,Yes,2025-08-01,162200000.0,1:53,86100000,2025 H2,Movie
4,The Old Guard 2,Yes,2025-07-02,145300000.0,1:47,81500000,2025 H2,Movie

In [37]:
df_2025_h2 = pd.concat(
    [df_2025_h2_shows, df_2025_h2_movies],
    ignore_index=True
)

df_2025_h2.shape

(16474, 8)

In [38]:
df_2025_h2["Content Type"].value_counts()

Content Type
Movie    8726
Show     7748
Name: count, dtype: int64

In [39]:
df_2026_h1_shows = pd.read_excel(
    "../data/raw/Netflix-s_What_We_Watched_Report_2026Jan-Jun__1_.xlsx",
    sheet_name="Shows",
    header=5
)

df_2026_h1_shows.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,His & Hers: Limited Series,Yes,2026-01-08,454300000.0,4:22,104000000
1,NaN,Bridgerton: Season 4,Yes,2026-01-29,889800000.0,8:53,100200000
2,NaN,I Will Find You: Limited Series,Yes,2026-06-18,350500000.0,5:29,63900000
3,NaN,Stranger Things 5,Yes,2025-11-26,578400000.0,10:24,55600000
4,NaN,Run Away: Limited Series,Yes,2026-01-01,315300000.0,6:16,50300000

In [40]:
df_2026_h1_shows = df_2026_h1_shows.drop(columns=["Unnamed: 0"])

df_2026_h1_shows["Report Period"] = "2026 H1"
df_2026_h1_shows["Content Type"] = "Show"

df_2026_h1_shows.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,His & Hers: Limited Series,Yes,2026-01-08,454300000.0,4:22,104000000,2026 H1,Show
1,Bridgerton: Season 4,Yes,2026-01-29,889800000.0,8:53,100200000,2026 H1,Show
2,I Will Find You: Limited Series,Yes,2026-06-18,350500000.0,5:29,63900000,2026 H1,Show
3,Stranger Things 5,Yes,2025-11-26,578400000.0,10:24,55600000,2026 H1,Show
4,Run Away: Limited Series,Yes,2026-01-01,315300000.0,6:16,50300000,2026 H1,Show

In [41]:
df_2026_h1_movies = pd.read_excel(
    "../data/raw/Netflix-s_What_We_Watched_Report_2026Jan-Jun__1_.xlsx",
    sheet_name="Movies",
    header=5
)

df_2026_h1_movies.head()

,Unnamed: 0,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views
0,NaN,War Machine,Yes,2026-03-06,266800000.0,1:49,146900000
1,NaN,The Rip,Yes,2026-01-16,256400000.0,1:53,136100000
2,NaN,Swapped,Yes,2026-05-01,222400000.0,1:42,130800000
3,NaN,KPop Demon Hunters,Yes,2025-06-20,217300000.0,1:40,130400000
4,NaN,Apex,Yes,2026-04-24,204200000.0,1:35,129000000

In [42]:
df_2026_h1_movies = df_2026_h1_movies.drop(columns=["Unnamed: 0"])

df_2026_h1_movies["Report Period"] = "2026 H1"
df_2026_h1_movies["Content Type"] = "Movie"

df_2026_h1_movies.head()

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
0,War Machine,Yes,2026-03-06,266800000.0,1:49,146900000,2026 H1,Movie
1,The Rip,Yes,2026-01-16,256400000.0,1:53,136100000,2026 H1,Movie
2,Swapped,Yes,2026-05-01,222400000.0,1:42,130800000,2026 H1,Movie
3,KPop Demon Hunters,Yes,2025-06-20,217300000.0,1:40,130400000,2026 H1,Movie
4,Apex,Yes,2026-04-24,204200000.0,1:35,129000000,2026 H1,Movie

In [43]:
df_2026_h1 = pd.concat(
    [df_2026_h1_shows, df_2026_h1_movies],
    ignore_index=True
)

df_2026_h1.shape

(17376, 8)

In [44]:
df_2026_h1["Content Type"].value_counts()

Content Type
Movie    9180
Show     8196
Name: count, dtype: int64

In [45]:
df_netflix = pd.concat(
    [
        df_2023_h1,
        df_2023_h2,
        df_2024_h1,
        df_2024_h2,
        df_2025_h1,
        df_2025_h2,
        df_2026_h1
    ],
    ignore_index=True
)

df_netflix.shape

(115964, 8)

In [46]:
df_netflix["Report Period"].value_counts().sort_index()

Report Period
2023 H1    18214
2023 H2    15994
2024 H1    16161
2024 H2    15563
2025 H1    16182
2025 H2    16474
2026 H1    17376
Name: count, dtype: int64

In [47]:
df_netflix.dtypes

Title                      str
Available Globally?        str
Release Date            object
Hours Viewed           float64
Runtime                 object
Views                   object
Report Period              str
Content Type            object
dtype: object

In [48]:
df_netflix.isna().sum()

Title                      4
Available Globally?        8
Release Date           78848
Hours Viewed               8
Runtime                18222
Views                  18222
Report Period              0
Content Type           18214
dtype: int64

In [49]:
df_netflix.groupby("Report Period")["Release Date"].apply(
    lambda x: x.isna().sum()
)

Report Period
2023 H1    13359
2023 H2    11026
2024 H1    11092
2024 H2    10579
2025 H1    10708
2025 H2    10756
2026 H1    11328
Name: Release Date, dtype: int64

In [50]:
df_netflix[df_netflix["Hours Viewed"].isna()]

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
89860,NaN,NaN,NaN,NaN,NaN,NaN,2025 H2,Show
89861,*The 2025 H2 report includes two additional ro...,NaN,NaN,NaN,NaN,NaN,2025 H2,Show
98586,NaN,NaN,NaN,NaN,NaN,NaN,2025 H2,Movie
98587,*The 2025 H2 report includes two additional ro...,NaN,NaN,NaN,NaN,NaN,2025 H2,Movie
106782,NaN,NaN,NaN,NaN,NaN,NaN,2026 H1,Show
106783,*“Other Movies” and “Other Shows” rows in this...,NaN,NaN,NaN,NaN,NaN,2026 H1,Show
115962,NaN,NaN,NaN,NaN,NaN,NaN,2026 H1,Movie
115963,*“Other Movies” and “Other Shows” rows in this...,NaN,NaN,NaN,NaN,NaN,2026 H1,Movie

In [51]:
df_netflix = df_netflix.dropna(subset=["Hours Viewed"])

df_netflix.shape

(115956, 8)

In [52]:
df_netflix["Title"].isna().sum()

np.int64(0)

In [53]:
df_netflix["Available Globally?"].isna().sum()

np.int64(0)

In [54]:
df_netflix.isna().sum()

Title                      0
Available Globally?        0
Release Date           78840
Hours Viewed               0
Runtime                18214
Views                  18214
Report Period              0
Content Type           18214
dtype: int64

In [55]:
df_netflix.groupby("Report Period")["Views"].apply(
    lambda x: x.isna().sum()
)

Report Period
2023 H1    18214
2023 H2        0
2024 H1        0
2024 H2        0
2025 H1        0
2025 H2        0
2026 H1        0
Name: Views, dtype: int64

In [57]:
df_netflix.groupby("Report Period")["Runtime"].apply(
    lambda x: x.isna().sum()
    )

Report Period
2023 H1    18214
2023 H2        0
2024 H1        0
2024 H2        0
2025 H1        0
2025 H2        0
2026 H1        0
Name: Runtime, dtype: int64

In [58]:
df_netflix.groupby("Report Period")["Content Type"].apply(
    lambda x: x.isna().sum()
)

Report Period
2023 H1    18214
2023 H2        0
2024 H1        0
2024 H2        0
2025 H1        0
2025 H2        0
2026 H1        0
Name: Content Type, dtype: int64

In [59]:
df_netflix["Release Date"] = pd.to_datetime(
    df_netflix["Release Date"],
    errors="coerce"
)

df_netflix["Release Date"].dtype

dtype('<M8[us]')

In [60]:
(df_netflix["Hours Viewed"] % 1 != 0).sum()

np.int64(0)

In [61]:
df_netflix["Hours Viewed"] = df_netflix["Hours Viewed"].astype("int64")

df_netflix["Hours Viewed"].dtype

dtype('int64')

In [63]:
df_netflix["Views"].apply(type).value_counts()

Views
<class 'int'>                         97738
<class 'pandas.api.typing.NAType'>    18214
<class 'str'>                             4
Name: count, dtype: int64

In [64]:
df_netflix[df_netflix["Views"].apply(lambda x: isinstance(x, str))]

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
89859,Other Shows,*,NaT,659000000,*,*,2025 H2,Show
98585,Other Movies,*,NaT,98200000,*,*,2025 H2,Movie
106781,Other Shows,*,NaT,757000000,*,*,2026 H1,Show
115961,Other Movies,*,NaT,102900000,*,*,2026 H1,Movie

In [65]:
df_netflix["Views"] = df_netflix["Views"].replace("*", pd.NA)

df_netflix["Views"].apply(type).value_counts()

Views
<class 'int'>                         97738
<class 'pandas.api.typing.NAType'>    18218
Name: count, dtype: int64

In [66]:
df_netflix["Views"] = df_netflix["Views"].astype("Int64")

df_netflix["Views"].dtype

Int64Dtype()

In [67]:
df_netflix["Runtime"].apply(type).value_counts()

Runtime
<class 'str'>                         97742
<class 'pandas.api.typing.NAType'>    18214
Name: count, dtype: int64

In [68]:
(df_netflix["Runtime"] == "*").sum()

np.int64(1072)

In [69]:
df_netflix[df_netflix["Runtime"] == "*"]["Report Period"].value_counts().sort_index()

Report Period
2023 H2    171
2024 H1    188
2024 H2    172
2025 H1    171
2025 H2    175
2026 H1    195
Name: count, dtype: int64

In [70]:
df_netflix[df_netflix["Runtime"] == "*"][
    ["Title", "Hours Viewed", "Views", "Report Period", "Content Type"]
].head(20)

,Title,Hours Viewed,Views,Report Period,Content Type
18234,Suits (2011): Season 1,247700000,26900000,2023 H2,Show
18264,Peppa Pig: Season 1,73000000,17900000,2023 H2,Show
18282,My Demon: Limited Series // 마이 데몬: 리미티드 시리즈,151800000,14900000,2023 H2,Show
18295,Peppa Pig: Season 2,56500000,13900000,2023 H2,Show
18296,Suits (2011): Season 7,161300000,13800000,2023 H2,Show
18301,Masha and the Bear: Season 5,42500000,13300000,2023 H2,Show
18427,Money Heist: Part 1 // La casa de papel: Parte 1,77700000,7500000,2023 H2,Show
18531,SpongeBob SquarePants: Season 5,46700000,5700000,2023 H2,Show
18533,Money Heist: Part 2 // La casa de papel: Parte 2,39200000,5700000,2023 H2,Show
18554,Gossip Girl (2007): Season 6,39200000,5500000,2023 H2,Show
18581,The Walking Dead: Season 11,81400000,5200000,2023 H2,Show
18629,Welcome to Samdal-ri: Limited Series // 웰컴투 삼달...,48200000,4700000,2023 H2,Show
18630,Friends (1994): Season 9,45900000,4700000,2023 H2,Show
18695,Miraculous: Tales of Ladybug & Cat Noir: Seaso...,19100000,4300000,2023 H2,Show
18705,Hunter X Hunter (2011): Season 1 // HUNTER×HUN...,43100000,4200000,2023 H2,Show
18715,The Children’s Kingdom: Zenon The Farmer // El...,10700000,4200000,2023 H2,Show
18723,LEGO Ninjago: Dragons Rising: Season 1,29900000,4100000,2023 H2,Show
18728,Miraculous: Tales of Ladybug & Cat Noir: Seaso...,17800000,4100000,2023 H2,Show
18739,Hunter X Hunter (2011): Season 2 // HUNTER×HUN...,19100000,4000000,2023 H2,Show
18750,Avatar: The Last Airbender (2005): Book 2,32000000,3900000,2023 H2,Show

In [71]:
df_netflix[df_netflix["Runtime"] == "*"]["Content Type"].value_counts()

Content Type
Show     1070
Movie       2
Name: count, dtype: int64

In [73]:
df_netflix[
    (df_netflix["Runtime"] == "*") &
    (df_netflix["Content Type"] == "Movie")
]

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type
98585,Other Movies,*,NaT,98200000,*,<NA>,2025 H2,Movie
115961,Other Movies,*,NaT,102900000,*,<NA>,2026 H1,Movie

In [74]:
df_netflix["Runtime"] = df_netflix["Runtime"].replace("*", pd.NA)

df_netflix["Runtime"].isna().sum()

np.int64(19286)

In [75]:
df_netflix["Runtime"].dropna().unique()[:20]

array(['7:34', '4:49', '5:43', '5:31', '7:36', '8:06', '4:45', '1:04',
       '9:16', '8:11', '4:59', '3:50', '7:37', '19:00', '8:10', '2:58',
       '2:26', '4:32', '8:17', '6:50'], dtype=object)

In [76]:
df_netflix["Runtime Minutes"] = (
    pd.to_timedelta(df_netflix["Runtime"] + ":00").dt.total_seconds() / 60
)

df_netflix[["Runtime", "Runtime Minutes"]].head()

  Runtime  Runtime Minutes
0    <NA>              NaN
1    <NA>              NaN
2    <NA>              NaN
3    <NA>              NaN
4    <NA>              NaN

In [77]:
df_netflix[
    df_netflix["Runtime"].notna()
][["Runtime", "Runtime Minutes"]].head(10)

      Runtime  Runtime Minutes
18214    7:34            454.0
18215    4:49            289.0
18216    5:43            343.0
18217    5:31            331.0
18218    7:36            456.0
18219    8:06            486.0
18220    4:45            285.0
18221    1:04             64.0
18222    9:16            556.0
18223    8:11            491.0

In [78]:
df_netflix["Runtime Minutes"].dtype

dtype('float64')

In [79]:
df_netflix["Runtime Minutes"] = df_netflix["Runtime Minutes"].astype("Int64")

df_netflix["Runtime Minutes"].dtype

Int64Dtype()

In [80]:
df_netflix["Available Globally?"].value_counts(dropna=False)

Available Globally?
No     83197
Yes    32755
*          4
Name: count, dtype: int64

In [81]:
df_netflix[df_netflix["Available Globally?"] == "*"][
    ["Title", "Report Period", "Content Type", "Available Globally?"]
]

               Title Report Period Content Type Available Globally?
89859    Other Shows       2025 H2         Show                   *
98585   Other Movies       2025 H2        Movie                   *
106781   Other Shows       2026 H1         Show                   *
115961  Other Movies       2026 H1        Movie                   *

In [82]:
df_netflix["Available Globally?"] = (
    df_netflix["Available Globally?"].replace("*", pd.NA)
)

df_netflix["Available Globally?"].value_counts(dropna=False)

Available Globally?
No     83197
Yes    32755
NaN        4
Name: count, dtype: int64

In [83]:
df_netflix["Content Type"].value_counts(dropna=False)

Content Type
Movie    54011
Show     43731
<NA>     18214
Name: count, dtype: int64

In [84]:
df_netflix.dtypes

Title                             str
Available Globally?               str
Release Date           datetime64[us]
Hours Viewed                    int64
Runtime                        object
Views                           Int64
Report Period                     str
Content Type                   object
Runtime Minutes                 Int64
dtype: object

In [85]:
df_netflix.duplicated().sum()

np.int64(0)

In [86]:
df_netflix.duplicated(
    subset=["Title", "Report Period"]
).sum()

np.int64(14)

In [87]:
df_netflix[
    df_netflix.duplicated(
        subset=["Title", "Report Period"],
        keep=False
    )
].sort_values(["Report Period", "Title"])

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type,Runtime Minutes
41460,Monster,Yes,2024-05-16,9800000,1:25,6900000,2024 H1,Movie,85
43807,Monster,Yes,2021-05-07,1300000,1:39,800000,2024 H1,Movie,99
58654,Maria,No,2024-12-11,4400000,2:03,2100000,2024 H2,Movie,123
59917,Maria,No,2019-05-17,1200000,1:30,800000,2024 H2,Movie,90
58683,Monster,Yes,2024-05-16,3000000,1:25,2100000,2024 H2,Movie,85
60609,Monster,Yes,2021-05-07,800000,1:39,500000,2024 H2,Movie,99
76059,Animals on the Loose: A You vs. Wild Movie,No,2025-01-23,600000,0:43,800000,2025 H1,Movie,43
77241,Animals on the Loose: A You vs. Wild Movie,No,2021-02-16,300000,0:45,400000,2025 H1,Movie,45
75391,Maria,No,2024-12-11,2400000,2:03,1200000,2025 H1,Movie,123
75860,Maria,No,2019-05-17,1300000,1:30,900000,2025 H1,Movie,90
75465,Monster,Yes,2024-05-16,1700000,1:25,1200000,2025 H1,Movie,85
76413,Monster,Yes,2021-05-07,1000000,1:39,600000,2025 H1,Movie,99
76815,You vs. Wild: Out Cold,No,2021-09-14,200000,0:25,500000,2025 H1,Movie,25
77251,You vs. Wild: Out Cold,No,2025-01-23,200000,0:29,400000,2025 H1,Movie,29
68770,You vs. Wild: Season 1,No,2025-01-23,1500000,2:12,700000,2025 H1,Show,132
71339,You vs. Wild: Season 1,No,2019-04-10,500000,2:31,200000,2025 H1,Show,151
92806,Maria,No,2019-05-17,1000000,1:30,700000,2025 H2,Movie,90
93155,Maria,No,2024-12-11,1000000,2:03,500000,2025 H2,Movie,123
92285,Monster,Yes,2024-05-16,1400000,1:25,1000000,2025 H2,Movie,85
94087,Monster,Yes,2021-05-07,500000,1:39,300000,2025 H2,Movie,99
87547,Solo Camping for Two (2025): Season 1 // ふたりソロ...,No,NaT,800000,4:45,200000,2025 H2,Show,285
89312,Solo Camping for Two (2025): Season 1 // ふたりソロ...,No,NaT,300000,3:18,100000,2025 H2,Show,198
110049,Maria,No,2019-05-17,900000,1:30,600000,2026 H1,Movie,90
111776,Maria,No,2024-12-11,400000,2:03,200000,2026 H1,Movie,123
109588,Monster,Yes,2024-05-16,1100000,1:25,800000,2026 H1,Movie,85
111785,Monster,Yes,2021-05-07,400000,1:39,200000,2026 H1,Movie,99
106784,War Machine,Yes,2026-03-06,266800000,1:49,146900000,2026 H1,Movie,109
110478,War Machine,Yes,2017-05-26,900000,2:03,400000,2026 H1,Movie,123

In [88]:
df_netflix.duplicated(
    subset=["Title", "Release Date", "Report Period"]
).sum()

np.int64(1)

In [89]:
df_netflix[
    df_netflix.duplicated(
        subset=["Title", "Release Date", "Report Period"],
        keep=False
    )
]

,Title,Available Globally?,Release Date,Hours Viewed,Runtime,Views,Report Period,Content Type,Runtime Minutes
87547,Solo Camping for Two (2025): Season 1 // ふたりソロ...,No,NaT,800000,4:45,200000,2025 H2,Show,285
89312,Solo Camping for Two (2025): Season 1 // ふたりソロ...,No,NaT,300000,3:18,100000,2025 H2,Show,198

In [90]:
df_netflix = df_netflix.reset_index(drop=True)

df_netflix.shape

(115956, 9)

In [91]:
df_netflix.isna().sum()

Title                      0
Available Globally?        4
Release Date           78844
Hours Viewed               0
Runtime                19286
Views                  18218
Report Period              0
Content Type           18214
Runtime Minutes        19286
dtype: int64

In [92]:
df_netflix[df_netflix["Title"].isin(["Other Shows", "Other Movies"])][
    ["Title", "Release Date", "Report Period"]
]

               Title Release Date Report Period
89859    Other Shows          NaT       2025 H2
98583   Other Movies          NaT       2025 H2
106777   Other Shows          NaT       2026 H1
115955  Other Movies          NaT       2026 H1

In [93]:
df_netflix.dtypes

Title                             str
Available Globally?               str
Release Date           datetime64[us]
Hours Viewed                    int64
Runtime                        object
Views                           Int64
Report Period                     str
Content Type                   object
Runtime Minutes                 Int64
dtype: object

In [94]:
df_netflix.to_csv(
    "../data/processed/netflix_engagement_clean.csv",
    index=False
)